"""
api/main.py

FastAPI inference service for the FinShield Fraud Detection Platform.

What this file does, in plain terms
------------------------------------
It wraps the trained model (`models/model.joblib`, produced by
`python -m src.train`) in a small web API so a transaction can be scored
in real time over HTTP, instead of only from a notebook or script.

    POST /predict   -> score one transaction, get back a fraud probability
                        and a flag/tier decision
    GET  /health     -> check the service is up and the model is loaded
    GET  /docs       -> interactive API documentation (auto-generated by
                        FastAPI from the type hints and docstrings below -
                        you can literally try requests from the browser)

How it stays correct
---------------------
This file does NOT reimplement any feature engineering or scoring logic.
Every request is scored through `src.predict.predict_one`, which is the
same function used by notebooks and tests, built on top of
`src.feature_engineering.create_features` - the same code path used at
training time. That is what prevents "train/serve skew": the API can
never accidentally featurize a transaction differently than the model
was trained on, because there is only one implementation of that logic
in the whole project, not one per consumer.

Running it locally
-------------------
    uvicorn api.main:app --reload
Then open http://127.0.0.1:8000/docs in a browser.
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import datetime
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, field_validator

from src import predict
from src.utils import get_logger, load_model_metadata

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Request / response schemas
#
# These are Pydantic models: FastAPI uses them both to VALIDATE incoming
# requests automatically (a request with a missing field, wrong type, or an
# invalid category gets rejected with a clear error before our code even
# runs) and to GENERATE the interactive docs at /docs.
# ---------------------------------------------------------------------------

class TransactionRequest(BaseModel):
    """
    Raw fields describing a single transaction plus the customer's
    profile/history at the moment it happened. These are exactly the
    fields `src.predict.REQUIRED_RAW_FIELDS` expects - everything else the
    model needs (risk signals, behavioral features) is computed
    automatically from these.

    The `Literal` types below restrict a field to a fixed set of valid
    values. This isn't just cosmetic: `feature_engineering.compute_risk_
    signals` maps `channel` and `merchant_category` to hand-picked risk
    weights (see `data_generation.py`); an unmapped value would silently
    produce a missing feature instead of a clear error, so validating the
    allowed values here is a real correctness safeguard, not decoration.
    """

    # --- Transaction fields ---
    transaction_type: Literal["card", "digital_payment"] = Field(
        ..., description="Payment rail used for the transaction."
    )
    merchant_category: Literal[
        "grocery", "electronics", "travel", "fashion",
        "gaming", "restaurants", "fuel", "utilities",
    ] = Field(..., description="Category of the merchant.")
    transaction_amount: float = Field(
        ..., gt=0, description="Monetary value of the transaction, must be positive."
    )
    channel: Literal["app", "web", "pos"] = Field(
        ..., description="Channel the transaction was made through."
    )
    device_type: Literal["ios", "android", "desktop"] = Field(
        ..., description="Device used for this specific transaction."
    )
    transaction_city: str = Field(..., description="City where the transaction took place.")
    merchant_risk_score: float = Field(
        ..., ge=0, le=1, description="Synthetic merchant risk score in [0, 1]."
    )
    timestamp: datetime = Field(
        ..., description="Date and time of the transaction (ISO 8601, e.g. 2025-06-15T14:00:00)."
    )

    # --- Customer profile / history at the time of the transaction ---
    customer_home_city: str = Field(..., description="Customer's registered home city.")
    customer_tenure_days: int = Field(..., ge=0, description="Days since the customer joined.")
    account_age_days: int = Field(..., ge=0, description="Days since the account was created.")
    preferred_device_type: Literal["ios", "android", "desktop"] = Field(
        ..., description="Customer's usual device type."
    )
    avg_amount_30d: float = Field(..., ge=0, description="Customer's average transaction amount, last 30 days.")
    std_amount_30d: float = Field(..., ge=0, description="Std. dev. of the customer's amounts, last 30 days.")
    transactions_last_7d: int = Field(..., ge=0, description="Number of the customer's transactions, last 7 days.")
    declines_last_30d: int = Field(..., ge=0, description="Number of declined transactions, last 30 days.")
    chargebacks_last_90d: int = Field(..., ge=0, description="Number of chargebacks, last 90 days.")

    @field_validator("transaction_city", "customer_home_city")
    @classmethod
    def _not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("must not be blank")
        return value

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "transaction_type": "digital_payment",
                    "merchant_category": "electronics",
                    "transaction_amount": 900.0,
                    "channel": "web",
                    "device_type": "android",
                    "transaction_city": "Miami",
                    "merchant_risk_score": 0.9,
                    "timestamp": "2025-06-15T02:30:00",
                    "customer_home_city": "Brooklyn",
                    "customer_tenure_days": 900,
                    "account_age_days": 900,
                    "preferred_device_type": "ios",
                    "avg_amount_30d": 50.0,
                    "std_amount_30d": 20.0,
                    "transactions_last_7d": 5,
                    "declines_last_30d": 0,
                    "chargebacks_last_90d": 0,
                }
            ]
        }
    }


class PredictionResponse(BaseModel):
    """What the model decided about the submitted transaction."""

    fraud_probability: float = Field(..., description="Model's estimated probability of fraud, in [0, 1].")
    is_fraud: bool = Field(..., description="True if fraud_probability >= decision_threshold.")
    risk_tier: Literal["low", "medium", "high", "critical"] = Field(
        ..., description="Human-readable risk bucket, scaled relative to the decision threshold."
    )
    decision_threshold: float = Field(
        ..., description="The business-cost-optimal threshold used to make the is_fraud decision (see Phase 2 / final_report.md)."
    )


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    model_loaded: bool
    model_name: str | None = Field(None, description="Name of the trained model in use, e.g. 'logistic_regression'.")
    decision_threshold: float | None = Field(None, description="Decision threshold currently in use.")


# ---------------------------------------------------------------------------
# App startup: load the model once, not on every request
#
# `predict.load_model()` and `predict.load_threshold()` are cached
# (functools.lru_cache), so calling them here just means the *first* call
# happens at startup - if the model file is missing, the service fails to
# start with a clear error instead of the first user request failing.
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting up: loading model and decision threshold...")
    predict.load_model()
    predict.load_threshold()
    logger.info("Model loaded and ready to serve predictions.")
    yield
    logger.info("Shutting down.")


app = FastAPI(
    title="FinShield Fraud Detection API",
    description=(
        "Real-time fraud scoring for card and digital payment transactions. "
        "Trained on a synthetic fintech dataset - see the project README and "
        "`outputs/reports/final_report.md` for the full model comparison and "
        "business rationale behind the decision threshold used here."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Permissive CORS so the project's Streamlit demo (or a browser-based caller
# trying this API out) can reach it without extra configuration. For a real
# production deployment this should be locked down to known origins.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", include_in_schema=False)
def root() -> dict:
    return {"message": "FinShield Fraud Detection API. See /docs for interactive documentation."}


@app.get("/health", response_model=HealthResponse, tags=["Monitoring"])
def health() -> HealthResponse:
    """
    Liveness/readiness check. Returns whether the model is loaded and which
    model + threshold are currently serving predictions, so a caller (or a
    deployment platform's health check) can confirm the service is actually
    able to score transactions, not just that the process is running.
    """
    try:
        metadata = load_model_metadata()
        predict.load_model()  # no-op if already cached; raises if the file is missing
        return HealthResponse(
            model_loaded=True,
            model_name=metadata.get("model_name"),
            decision_threshold=metadata.get("decision_threshold"),
        )
    except FileNotFoundError:
        return HealthResponse(model_loaded=False)


@app.post("/predict", response_model=PredictionResponse, tags=["Inference"])
def predict_transaction(transaction: TransactionRequest) -> PredictionResponse:
    """
    Score a single transaction and return the model's fraud decision.

    Validation happens in two layers:
    1. Pydantic (this request model) rejects malformed requests - missing
       fields, wrong types, out-of-range values, invalid categories -
       before any of our code runs.
    2. `src.predict.predict_one` re-validates that feature computation
       produced every column the model expects, and raises if not. That
       should be unreachable given layer 1, but it is kept as a safety net
       (see the fail-loud design in `feature_engineering.get_modeling_data`).
    """
    payload = transaction.model_dump()
    payload["timestamp"] = transaction.timestamp.isoformat()

    try:
        result = predict.predict_one(payload)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    return PredictionResponse(
        fraud_probability=result["fraud_probability"],
        is_fraud=result["is_fraud"],
        risk_tier=result["risk_tier"],
        decision_threshold=result["decision_threshold"],
    )
